name: Spider_laoZ

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK
      uses: actions/setup-java@v3.11.0
      with:
        java-version: '18'
        distribution: 'temurin'
        
    - name: Clone project
      run: |
        rm -rf project
        rm -rf jar/custom_spider.jar
        git clone --recurse-submodules https://github.com/FongMi/CatVodSpider project
      
    - name: Customize Spider
      working-directory: ./project
      run: |
         #添加Misc&douban
         curl -L https://github.com/zhixc/CatVodTVSpider/raw/main/app/src/main/java/com/github/catvod/utils/Misc.java > app/src/main/java/com/github/catvod/utils/Misc.java
         curl -L https://github.com/zhixc/CatVodTVSpider/raw/main/app/src/main/java/com/github/catvod/spider/DoubanForTVBox.java > app/src/main/java/com/github/catvod/spider/DoubanForTVBox.java
         curl -L https://github.com/zhixc/CatVodTVSpider/raw/main/app/src/main/java/com/github/catvod/spider/Douban.java > app/src/main/java/com/github/catvod/spider/Douban.java
                 
         #添加AppYsV2
         #curl -L https://raw.githubusercontent.com/zhixc/CatVodTVSpider/main/app/src/main/java/com/github/catvod/spider/AppYsV2.java > app/src/main/java/com/github/catvod/spider/AppYsV2.java
         #sed -i 's/com.github.catvod.utils.okhttp.OkHttpUtil/com.github.catvod.net.OkHttp/g;s/OkHttpUtil/OkHttp/g' app/src/main/java/com/github/catvod/spider/AppYsV2.java

                 
         #添加Live2Vod
         #curl -L https://github.com/zhixc/CatVodTVSpider/raw/main/app/src/main/java/com/github/catvod/bean/Live.java > app/src/main/java/com/github/catvod/bean/Live.java
         #curl -L https://github.com/zhixc/CatVodTVSpider/raw/main/app/src/main/java/com/github/catvod/spider/Live2Vod.java > app/src/main/java/com/github/catvod/spider/Live2Vod.java         
         #sed -i 's/com.github.catvod.utils.okhttp.OkHttpUtil/com.github.catvod.net.OkHttp/g;s/OkHttpUtil/OkHttp/g' app/src/main/java/com/github/catvod/spider/Live2Vod.java

         #添加JavDb from cnxunyang
         #curl -L https://github.com/cnxuyang/CatVodTVSpider/raw/main/app/src/main/java/com/github/catvod/spider/JavDb.java > app/src/main/java/com/github/catvod/spider/JavDb.java

         #添加wogg&oiltea         
         #curl -L https://github.com/oiltea/CatVodSpider/blob/7f8873c20c4fa139b6d44cb11c3981a4bfebe6b2/app/src/main/java/com/github/catvod/spider/Wogg.java > app/src/main/java/com/github/catvod/spider/Wogg.java
         #curl -L https://github.com/oiltea/CatVodSpider/raw/9ab5cc627be4096db11bca9ee9177c13014ddadd/app/src/main/java/com/github/catvod/spider/Wogg.java > app/src/main/java/com/github/catvod/spider/Wogg.java
         #curl -L https://github.com/oiltea/CatVodSpider/raw/9ab5cc627be4096db11bca9ee9177c13014ddadd/app/src/main/java/com/github/catvod/spider/Wogg.java > app/src/main/java/com/github/catvod/spider/Wooggg.java
          
         #简体化阿里云盘
         sed -i 's/原畫/原画(4K)/g;s/普畫/普画(1080P)/g' app/src/main/java/com/github/catvod/spider/Ali.java
         sed -i 's/原畫/原画(4K)/g;s/普畫/普画(1080P)/g;s/阿里雲盤/阿里云盘/g;s/請輸入Token/请輸入Token/g;s/請使用阿里雲盤 App 掃描二維碼/请使用阿里云盘 App 扫描二维码/g;s/來晚啦，該分享已失效/来晚了，木有了，换一个/g' app/src/main/java/com/github/catvod/api/AliYun.java
         #sed -i 's/https:\/\/s1.ax1x.com\/2023\/05\/04\/p9tgI81.png/http:\/\/image.coolapk.com\/feed\/2023\/0817\/10\/15491134_1b0929b1_9775_1639_274@512x512.png/g' app/src/main/java/com/github/catvod/utils/Image.java
         
         #cp ../app/src/main/java/com/github/catvod/spider/Zhaozy.java app/src/main/java/com/github/catvod/spider/Zhaozy.java

         #cp ../app/src/main/java/com/github/catvod/spider/YiSo.java app/src/main/java/com/github/catvod/spider/YiSo.java
         
         #curl -L  https://github.com/FongMi/CatVodSpider/blob/747b71b526cbddce9eb76fa6a8eef057747cfc34/app/src/main/java/com/github/catvod/spider/YiSo.java > app/src/main/java/com/github/catvod/spider/YiSo.java
        
         #del lao six
         rm -rf app/src/main/java/com/github/catvod/spider/Doll.java
         rm -rf app/src/main/java/com/github/catvod/spider/Eighteen.java
         rm -rf app/src/main/java/com/github/catvod/spider/Jable.java
         rm -rf app/src/main/java/com/github/catvod/spider/Miss.java
         rm -rf app/src/main/java/com/github/catvod/spider/Supjav.java
         rm -rf app/src/main/java/com/github/catvod/spider/Hanime.java
                                 
         
         
    - name: Build the app
      working-directory: ./project
      run: |        
         chmod +x gradlew
         ./gradlew assemblerelease --build-cache --parallel --daemon --warning-mode all
         
    - name: Customize Spider Jar
      working-directory: ./project
      run: |        
         rm -rf jar/custom_spider.jar
         rm -rf jar/spider.jar/original/META-INF
         curl -L https://github.com/iBotPeaches/Apktool/releases/download/v2.7.0/apktool_2.7.0.jar > jar/3rd/apktool_2.7.0.jar
         java -jar jar/3rd/baksmali-2.5.2.jar d app/build/intermediates/dex/release/minifyReleaseWithR8/classes.dex -o jar/Smali_classes
         mkdir -p jar/spider.jar/smali/com/github/catvod/
         mv jar/Smali_classes/com/github/catvod/spider jar/spider.jar/smali/com/github/catvod/         
         java -jar jar/3rd/apktool_2.7.0.jar b jar/spider.jar -c
         mv jar/spider.jar/dist/dex.jar ../jar/custom_spider.jar
         md5=($(md5sum ../jar/custom_spider.jar))
         echo $md5 > ../jar/custom_spider.jar.md5
    - name: Upload APK
      uses: actions/upload-artifact@v3.1.2
      with:
        name: Spider
        path: ./jar/custom_spider.jar

    - name: Update spider jar      
      uses: EndBug/add-and-commit@v9.1.3
      with:
        default_author: github_actions
        message: 'update spider jar'
        add: "['./jar/custom_spider.jar', './jar/custom_spider.jar.md5']"        
